### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by Yorgg** [keijiro/jp.keijiro.rtmidi#1]
Hi,

This library is great, but I get ~100ms of constant latency.      
Is there any way to reduce it?

Windows 10
Unity 2019.3.0b5

I have used RTMidi on this machine before and didn't have latency issues. 

Thanks!

**Comment by keijiro** [comment]
I've never experienced such latency. There might be an unknown issue.

- How did you test it? Could you share the test project?
- Could you try my Minis examples and check if the same problem reproduces with it? https://github.com/keijiro/VfxMinisExamples

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen if it still reproduces.
