### ISSUE TITLE
MidiProbe and MidiOutPort could not be found

### ISSUE THREAD

**Issue by jrdndj** [keijiro/jp.keijiro.rtmidi#11]
tried the MidiOut.cs test file and so far we are encountering this issue.

`using RtMidi.LowLevel;` is red too. Ive added rtmidi on scope registries and check the previous issues. any help on this? 

thank you! 

additional info: i imported it into my existing project that is running on 2019.4.11f1 Windows 10.

**Comment by lloydmarquart** [comment]
same thing is happening for me as well!

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by jrdndj** [comment]
it worked for me. that was a stupid issue I guess. thanks for all the help!
