### ISSUE TITLE
DllNotFoundException: RtMidi.dll on mac OS

### ISSUE THREAD

**Issue by mrsolo5k** [keijiro/jp.keijiro.rtmidi#2]
I am trying to test the package inside my unity project. Unfortunately I get this error on start within editor with `MidiInTest.cs` example script present on an object in scene:

`
DllNotFoundException: RtMidi.dll
RtMidi.LowLevel.MidiProbe..ctor (RtMidi.LowLevel.MidiProbe+Mode mode) (at Assets/Scripts/RtMidi/MidiProbe.cs:16)
MidiInTest.Start () (at Assets/Scripts/RtMidi/MidiInTest.cs:56)
`

I use:
macOS High Sierra Version 10.13.6
Unity 2019.3.2f1

I installed the package by editing `Packages\manifest.json` as mentioned in README

**Comment by keijiro** [comment]
How about simply cloning this repository and running it on Editor? I this case, you don't have to edit the package manifest file (manifest.json).

**Comment by mrsolo5k** [comment]
Already tried simply cloning the repo. Getting same results.

**Comment by keijiro** [comment]
Unfortunately, it doesn't reproduce on my side (macOS 10.15.3, Unity 2019.3.4f1). I wonder if there is a macOS compatibility issue.

**Comment by YasuyukiOGINO** [comment]
Hi,
I get a similar problem.
 If it is possible, did you try run the builded app at another pc.
The one used build did run, but the other had the error ( DllNotFoundException: rtmidi.dll~ ) .

**Comment by felipe-torres** [comment]
After upgrading Unity to 2019.3.15f1 and opening the project in this version this problem was gone for me, if it helps anybody.

**Comment by in2ki** [comment]
I had the same Problem on MacOs High Sierra. Tried higher Unity versions but only updating to Mojave (10.14.6) fixed it. A macOs compatibility issue is very likely.

May someone enlighten me on another matter:
Is it somehow possible to send Pitch Bend data with RtMidi? Or is the wrapper too thin for that? It would be spare me the effort of diving into Juce...
Answer highly appreciated!

**Comment by keijiro** [comment]
@in2ki Please create a new issue for an unrelated topic.

**Comment by keijiro** [comment]
I think this issue was fixed in the latest update.

I'm closing this issue now. Please feel free to reopen it if it still reproduces.

**Comment by jfisher993** [comment]
@keijiro Seeing a similar issue on MacOS 18.1 Sequoia 15.1 and Unity 2022.3.62f1

`DllNotFoundException: RtMidi assembly:<unknown assembly> type:<unknown type> member:(null)
RtMidi.MidiIn.Create () (at ./Library/PackageCache/jp.keijiro.rtmidi@2.1.3/Runtime/MidiIn.cs:14)
Minis.MidiDriver.Update () (at ./Library/PackageCache/jp.keijiro.minis@1.3.1/Runtime/Internal/MidiDriver.cs:34)
Minis.MidiSystemWrangler+<>c.<InsertPlayerLoopSystem>b__2_0 () (at ./Library/PackageCache/jp.keijiro.minis@1.3.1/Runtime/Internal/MidiSystemWrangler.cs:43)
UnityEditor.EditorApplication:Internal_RestoreLastOpenedScenes() (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:561)`
