### ISSUE TITLE
DllNotFoundException: RtMidi.dll on build for MacOS

### ISSUE THREAD

**Issue by felipe-torres** [keijiro/jp.keijiro.rtmidi#3]
Hi! I´m getting these errors ([log here](https://pastebin.com/5SK2Re8v)) when testing a build made with this package, which causes the plugin to not work at all, even though there are no such errors when running in the editor (and the plugin works here too). 

I've tested both downloading this project directly and also following the instructions in the readme for installing it via the package manager, and I get the same results.

Thanks!

I'm using:
MacOS 10.14.6
Unity 2019.3.0f6

**Comment by keijiro** [comment]
Close as duplicate #2 

Thank you for reporting the problem. Unfortunately, I haven't reproduced the issue yet. I'll try some other Mac machines.
