### ISSUE TITLE
Port Already in Use

### ISSUE THREAD

**Issue by sachismo** [keijiro/jp.keijiro.rtmidi#4]
Thank you for the great plugin! I am using it for a midi translator app with good success. I have one small issue that is Windows specific: 

Windows still only allows one app at a time to use a hardware MIDI port. If I connect to a port that is already in use by another app, there are no errors thrown but my app will of course not actually be able to use the port..

Is there any way to get a notification if a connection fails in this way so that a GUI can notify you that this port is not able to work? 

Thanks for any info!

**Comment by keijiro** [comment]
I think the API returns null when it fails to open the port, like: https://github.com/keijiro/jp.keijiro.rtmidi/blob/master/Assets/MidiOutPort.cs#L14

**Comment by sachismo** [comment]
Thank you for the fast reply! I believe I see what's happening now.. On the line you point to, the check happens before the port is actually opened and never gets thrown.

        public MidiOutPort(int portNumber)
        {
            _rtmidi = RtMidiDll.OutCreateDefault();

            if (_rtmidi == null || !_rtmidi->ok)
                throw new System.InvalidOperationException("Failed to set up a MIDI output port.");

            RtMidiDll.OpenPort(_rtmidi, (uint)portNumber, "RtMidi Out");
        }

If I change the order to the following, it works as expected on both input and output ports and I can change the exception to my own error flags

        public MidiOutPort(int portNumber)
        {
            _rtmidi = RtMidiDll.OutCreateDefault();
            RtMidiDll.OpenPort(_rtmidi, (uint)portNumber, "RtMidi Out");

            if (_rtmidi == null || !_rtmidi->ok)
                throw new System.InvalidOperationException("Failed to set up a MIDI output port.");

            
        }

Let me know if this makes sense.. Also happy to do a quick PR if it helps :)

**Comment by keijiro** [comment]
Thanks for pointing it out. I slightly changed the related parts of the code in the latest commit: https://github.com/keijiro/jp.keijiro.rtmidi/commit/afcf6a784486604d5323d548a581b6337b0b552a
