### ISSUE TITLE
Send Pitch Bend data with RtMidi?

### ISSUE THREAD

**Issue by in2ki** [keijiro/jp.keijiro.rtmidi#6]
Is it somehow possible to send Pitch Bend data with RtMidi? This would spare me the great effort of programming this in Juce.
Answer highly appreciated!

_Originally posted by @in2ki in https://github.com/keijiro/jp.keijiro.rtmidi/issues/2#issuecomment-778820849_

**Comment by keijiro** [comment]
Possible.

For example, you can extend the sample script ([MidiOutPort.cs](https://github.com/keijiro/jp.keijiro.rtmidi/blob/master/Assets/MidiOutPort.cs)) to support pitch bend.

It sends note on messages like the following:

https://github.com/keijiro/jp.keijiro.rtmidi/blob/master/Assets/MidiOutPort.cs#L53

`0x90` means the note on event.

https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message

So, you can send pitch bend events using `0xe0`.

**Comment by keijiro** [comment]
I'm closing this issue now as resolved.
