### ISSUE TITLE
Ports not updating  (windows 10)

### ISSUE THREAD

**Issue by Yorgg** [keijiro/jp.keijiro.rtmidi#8]
I am using LoopMidi to create virtual ports on Windows.   
Issue =>  When I terminate these ports, rtMidi still sees them as available.

```cs
// Available ports
for(var i=0; i < _probe.PortCount, i++) {
    Debug.Log(_probe.GetPortName(i));   // <== outputs port that is already terminated!!
}
```

Any idea what's going on here?  Should I post this on the rtMidi repo?

Thanks!!!!

**Comment by keijiro** [comment]
`GetPortName` is directly mapped to `rtmidi_get_port_name`, so it does nothing in the C# side. I think it's a "by-design" behavior in the original code.

You can post it to the original rtmidi repository, but you should test it with C++ in that case.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
